market/apps/production/urls.py
from django.conf.urls import url

from apps.production.views import IndexView, CategoryView, DetailView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 商品首页
    url(r'^category/(?P<cate_id>\d+)/(?P<order>\d)/$', CategoryView.as_view(), name='category'),  # 商品分类（商品列表）
    url(r'^(?P<id>\d+).html$', DetailView.as_view(), name='detail'),  # 商品详情
]

market/apps/shoppingcart/urls.py
from django.conf.urls import url

from shoppingcart.views import AddCartView

urlpatterns = [
    url(r'^add/$',AddCartView.as_view(),name='addcart'),

]

market/apps/user/urls.py
from django.conf.urls import url

from user.views import LoginView, RegisterView, SendMsg

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 用户登录
    url(r'^reg/$', RegisterView.as_view(), name="register"),  # 用户注册
    url(r"^send_msg/$",SendMsg.as_view(),name='send_msg'), #发送信息
    #url(r'^member/$', member, name="member"),  # 用户中心
    # url(r'^detail/(?P<id>\d+)/$',detail,name="详情"),
    # url(r'^add/$',add,name="添加"),
    # url(r'^delete/(?P<id>\d+)/$',delete,name="删除"),
    # url(r'^edit/(?P<id>\d+)/$',edit,name="修改"),
    # url(r'^add_form/$',add_form,name="渲染form"),
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from production.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 绑定子路由
    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^production/',include('production.urls',namespace='production')),
    url(r'^shoppingcart/', include('shoppingcart.urls', namespace='shoppingcart')),
    url(r'^user/', include('user.urls', namespace='user')),
    #添加富文档子路由
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    #添加搜索子路由
    url(r'^search/', include('haystack.urls', namespace='search')),
]

market/apps/production/models.py
from django.db import models
from django.core.validators import RegexValidator
# Create your models here.
from db.base_model import BaseModel
from ckeditor_uploader.fields import RichTextUploadingField

class ProCategory(BaseModel):
    """
    商品分类
    ID
    分类名
    分类简介

    """
    category_name = models.CharField(max_length=32,
                                     verbose_name='分类名')
    category_introduce = models.CharField(max_length=200,
                                          verbose_name='分类简介',
                                          null=True,
                                          blank=True)
    category_order = models.SmallIntegerField(default=0,
                                              verbose_name="排序")

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = "分类管理"
        verbose_name_plural = verbose_name

class ProSPU(BaseModel):
    """
        商品SPU表
        ID
        名称
        详情
    """
    spu_name = models.CharField(max_length=32,
                                verbose_name='商品spu名')
    spu_introduce = RichTextUploadingField(verbose_name='商品spu详情')

    def __str__(self):
        return self.spu_name

    class Meta:
        verbose_name = "商品SPU管理"
        verbose_name_plural = verbose_name

class ProSKU(BaseModel):
    """
        商品SKU表
    """
    SHOW_STATUS_CHOICES = (
        (1, '上架'),
        (2, '下架'),
    )
    sku_name = models.CharField(max_length=100,
                                verbose_name='商品名')
    sku_introduce = RichTextUploadingField(verbose_name='商品简介',
                                           null=True,
                                           blank=True)
    sku_price = models.DecimalField(max_digits=9,
                                    decimal_places=2,
                                    verbose_name="商品价格",
                                    default=0,)
    sku_unit = models.ForeignKey(to="ProductUnit", verbose_name="单位")
    sku_inventory = models.IntegerField(verbose_name='商品库存',
                                        default=0)
    sku_sales_volume = models.IntegerField(verbose_name='商品销量',
                                           null=True,
                                           blank=True)
    sku_logo = models.ImageField(upload_to='pro_logo',
                                 verbose_name='商品LOGO地址',
                                 null=True,
                                 blank=True,
                                 max_length=500)
    sku_show = models.IntegerField(choices=SHOW_STATUS_CHOICES,
                                   verbose_name='上架状态',
                                   default=1)
    sku_category_id = models.ForeignKey(to='ProCategory',
                                        on_delete=models.CASCADE,
                                        verbose_name="商品分类id")
    sku_spu_id = models.ForeignKey(to='ProSPU',
                                   on_delete=models.CASCADE,
                                   verbose_name="商品spuid")

    def __str__(self):
        return self.sku_name

    class Meta:
        verbose_name = "商品SKU管理"
        verbose_name_plural = verbose_name




class PhotoAlbum(BaseModel):
    """
        商品相册
        ID
        图片地址
        商品SKUID

    """
    photo_url = models.ImageField(upload_to='pro_photo',
                                  verbose_name='图片地址',
                                  null=True,
                                  blank=True)
    photo_sku_id = models.ForeignKey(to='ProSKU',
                                     on_delete=models.CASCADE,
                                     verbose_name="图片sku_id")

    def __str__(self):
        return self.photo_url.__str__()

    class Meta:
        verbose_name = "商品相册管理"
        verbose_name_plural = verbose_name


class ProductUnit(BaseModel):
    """
        商品单位表
        ID
        单位名（斤，箱）

    """
    unit_name = models.CharField(max_length=10,
                                 verbose_name="商品单位",
                                 null= True,
                                 blank=True)

    def __str__(self):
        return self.unit_name

    class Meta:
        verbose_name = "商品单位管理"
        verbose_name_plural = verbose_name


class Banner(BaseModel):
    """
    首页轮播商品
    ID
    名称
    商品SKUID
    图片地址
    排序（order）

    """
    banner_name = models.CharField(max_length=32, verbose_name="轮播图名字")
    banner_sku_id = models.ForeignKey(to='ProSKU', on_delete=models.CASCADE, verbose_name="轮播sku_id")
    banner_url = models.ImageField(upload_to='banner', verbose_name='轮播图片地址', null=True, blank=True, max_length=500)
    banner_order = models.IntegerField(null=True, blank=True, verbose_name="排序")

    def __str__(self):
        return self.banner_name

    class Meta:
        verbose_name = "轮播图管理"
        verbose_name_plural = verbose_name


class Activity(models.Model):
    """
        首页活动表
        ID
        名称
        图片地址
        url地址 www.jd.com
    """
    activity_name = models.CharField(max_length=22, verbose_name="活动名字")
    activity_photo = models.ImageField(upload_to='activity', verbose_name='活动图片地址', null=True, blank=True,
                                       max_length=500)
    activity_address = models.URLField(max_length=500, verbose_name="活动链接地址")

    def __str__(self):
        return self.activity_name

    class Meta:
        verbose_name = "活动管理"
        verbose_name_plural = verbose_name


class ActivityRegion(BaseModel):
    """
        首页活动专区
        ID
        名称
        描述
        排序
        是否上架
        专区ID

    """
    SHOW_STATUS_CHOICES = (
        (1, '上架'),
        (2, '下架'),
    )
    region_name = models.CharField(max_length=22, verbose_name="专区名字")
    region_introduce = models.CharField(max_length=22,verbose_name="专区描述")
    region_order = models.IntegerField(verbose_name="专区排序")
    region_show = models.IntegerField(choices=SHOW_STATUS_CHOICES, verbose_name="上架状态", default=1)
    region_sku = models.ManyToManyField(to='ProSKU',verbose_name='商品')


    def __str__(self):
        return self.region_name

    class Meta:
        verbose_name = "活动专区管理"
        verbose_name_plural = verbose_name

market/apps/production/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View

# 商品首页
from production.models import ProSKU, ProCategory, Banner, Activity, ActivityRegion


class IndexView(View):
    def get(self,request):
        """首页"""
        # 获取轮播
        banners = Banner.objects.filter(is_delete=False).order_by("-order")

        # 获取活动
        acts = Activity.objects.filter(is_delete=False)

        # 获取特色专区
        act_zones = ActivityRegion.objects.filter(region_show =1, is_delete=False).order_by("-order")

        # 渲染数据
        context = {
            "banners": banners,
            "acts": acts,
            "act_zones": act_zones,
        }

        return render(request, "production/index.html", context)





# 商品分类(商品列表)
class CategoryView(View):

    def get(self,request,cate_id,order):
        try:
            cate_id = int(cate_id)
            order = int(order)
        except:
            return redirect("production:index")

        # 所有的分类 产品经理
        categorys = ProCategory.objects.filter(is_delete=False).order_by("-order")

        # 查询某个分类下的所有商品
        # 默认查询第一个分类
        if cate_id == 0:
            category = categorys.first()
            cate_id = category.pk

        goodsSkus = ProSKU.objects.filter(sku_show=1, is_delete=False , sku_category_id=cate_id)

        order_rule = ["id", "-sku_sales_volume", "-sku_price", "sku_price", "-create_time"]
        try:
            order_one = order_rule[order]
        except:
            order_one = order_rule[0]
            order = 0
        goodsSkus = goodsSkus.order_by(order_one)
        return render(request,'production/category.html')





# 商品详情
class DetailView(View):

    def get(self,request):
        prosku = ProSKU.objects.get(pk=id)

        # 渲染数据到页面
        context = {
            "prosku": prosku
        }
        return render(request,'production/detail.html')

market/production/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.
def production(request):
    html = "production "
    return HttpResponse(html)

market/templates/production/category.html
{% extends 'common/parent.html' %}
{% load static %}

{% block head_css %}
		<style>
			.shop-list-mid .tit a{
                color: #909090;
                font-size: 1.4rem;
                display: -webkit-box;
                -webkit-line-clamp: 1;
                -webkit-box-orient: vertical;
                overflow: hidden;
                white-space: normal;
                text-overflow: ellipsis;}
		</style>
{% endblock %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <form action="{% url 'search:haystack_search' %}" method="get">
            <div class="cate-search">
                <input type="text" name="q" value="" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
                <input type="submit" value="" class="cate-btn"/>
            </div>
        </form>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <ul class="list-nav">
        <li {% if order == 0 %}class="current"{% endif %}><a href="{% url 'production:category' cate_id 0 %}">综合</a></li>
        <li {% if order == 1 %}class="current"{% endif %}><a href="{% url 'production:category' cate_id 1 %}">销量</a></li>
        <li {% if order == 2 %}class="current"{% endif %}><a href="{% url 'production:category' cate_id 2 %}"><i
                class="list-price">价格</i></a></li>
        <li {% if order == 4 %}class="current"{% endif %}><a href="{% url 'production:category' cate_id 4 %}">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
           {% for category in categorys %}
                <li {% if cate_id == category.pk %}class="current"{% endif %}>
                    <a href="{% url 'production:category' category.pk order %}">{{ category.category_name }}</a>
                </li>
            {% endfor %}
        </div>



        <div class="list-right">
            <ul class="list-pro">
                {% for goods in goodsSkus %}
                <li>
                    <a href="{% url 'production:detail' goods.pk %}"><img src="{{ MEDIA_URL }}{{ goods.sku_logo }}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit">
                            <a href="detail.html">
                                {{ goods.sku_spu_id.spu_name }}&emsp;{{ goods.sku_name }}
                            </a>
                        </div>
                        <div class="am-gallery-desc">￥{{ goods.sku_price }}</div>
                        <p>销量：{{ goods.sku_sales_volume }}{{ goods.sku_unit }}</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                                <a class="decrease">-</a>
                                <input id="num" sku_id="{{ goods.pk }}" readonly="" class="text_box" name="" type="text" value="0">
                                <a class="increase">+</a>
                        </div>
                    </div>
                    <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                </li>
                {% empty %}
                <li>该分类下没有商品</li>
                {% endfor %}
            </ul>
        </div>
    </div>



	    <!--底部-->
     <div style="height: 55px;"></div>
     <div class="fix-bot">
	   	  <a href="{% url 'shoppingcart:index' %}"><div class="fix-bot-cart"><i id="cart_count">{{ cart_count }}</i></div></a>
	   	  <a href="tureorder.html" class="list-js">去结算</a>
	   	  <a href="tureorder.html" class="list-jsk">一键快购</a>
	   	  <!--<div class="js-text">
            	<p><b>￥217.80</b></p>
            	<p class="js-car">购物满50元免运费</p>
          </div>-->
 </div>
{% endblock %}
 
{% block footer_js %}
    <script>
    $(function () {
        //改变价格上的url地址
        if ("{{ order }}" == 2) {
            $(".list-price").parent("a").attr('href', "{% url 'production:category' cate_id 3 %}")
        } else if ("{{ order }}" == 3) {
            $(".list-price").parent("a").attr('href', "{% url 'sproduction:category' cate_id 2 %}")
        }
    });
    //购物数量加减
    $(function(){
		$('.increase').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			//购买商品的数量
			current_num += 1;
			var  count = 1;
			var  sku_id = self.siblings('input').attr('sku_id');
			//发送ajax到后台
			$.ajax({
                type:'post',
                url:'{% url 'shoppingcart:addcart' %}',
                data:{
                    'count':count,
                    'sku_id':sku_id,
                    'csrfmiddlewaretoken':'{{ csrf_token }}',
                },
                dataType : 'json',
                success : function (data) {
                    if(data.code == 0){
                        if (current_num>0){
                            self.siblings('.derease').fadeIn();
                            self.siblings('.text_box').fadeIn();

                        }
                        self.siblings('.input').val(current_num);
                        $('#cart_count').text(data.cart_count);
                    }else if (data.code == 1){
                        var flag = confirm('是否登陆');
                        if(flag){
                            location.href = {% url 'user:login' %}? next = {% url 'production:category' cate_id order %}
                        }
                    }
                }
            });
        });

        $('.decrease').click(function () {
            var self = $(this);
            var current_num = parseInt(self.siblings('input').val());
            if (current_num > 0) {
                 //发送ajax到后台 添加购物车数据
                //收集数据 count sku_id
                var count = -1;
                var sku_id = self.siblings('input').attr('sku_id');
                //发送ajax
                $.ajax({
                    type:'post',
                    url:'{% url "shoppingcart:addcart" %}',
                    data:{
                        "count":count,
                        "sku_id":sku_id,
                        "csrfmiddlewaretoken":"{{ csrf_token }}",
                    },
                    dataType:"json",
                    success:function (data) {
                        if(data.code == 0){
                            current_num -= 1;
                            if (current_num < 1) {
                                self.fadeOut();
                                self.siblings(".text_box").fadeOut();
                            }
                            self.siblings('input').val(current_num);
                            //更新购物车中总数量的显示
                            $("#cart_count").text(data.cart_count);
                        }else if (data.code == 1){
                            //跳转到登陆页面
                            var flag = confirm("没有登陆,是否立即登陆?");
                            if(flag){
                               location.href = "{% url 'user:login' %}?next={% url 'production:category' cate_id order %}"
                            }
                        }
                    }
                });
            }
        });
    })

</script>
{% endblock %}

market/templates/production/detail.html
{% extends 'common/parent.html' %}
{% load static %}
{% block head_js %}
		<script>
        	function changeImage(){
              document.getElementById("imgflag").src="{% static 'images/redherat.png' %}";
           }
        </script>
{% endblock %}
{% block head_css %}
		<style>
			.am-slider-default .am-control-nav{ text-align: center;}
			.am-slider-default .am-control-nav li a.am-active{ background: #cb2527;}
			.am-slider-default .am-control-nav li a{ border: 0; width: 10px; height: 10px;}
		</style>
{% endblock %}

{% block header %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">商品详情</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <!--图片轮换-->
		<div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
		  <ul class="am-slides">
            {% for v in prosku.photoalbum_set.all %}
                <li><img src="{{ MEDIA_URL }}{{ v.photo_url }}"/></li>
            {% endfor %}
		  </ul>
		</div>
		<div class="detal-info" style="position: relative; width: 100%;">
			<p>{{ prosku.sku_spu_id.spu_name }}&emsp;{{ prosku.sku_name }}</p>
			<h2>商城价：<span>￥{{ prosku.sku_price }}</span></h2>
			<div class="heart">
				<img src="{% static 'images/herat.png' %}" width="25" id="imgflag" onclick="changeImage()" />
				<p>收藏</p>
			</div>
		</div>
		<div class="d-amount">
        	<h4>数量：</h4>
            <div class="d-stock">
              <a class="decrease">-</a>
                <input id="num" readonly="" class="text_box" name="" type="text" value="1">
                <a class="increase">+</a>
               <span id="dprice" class="price" style="display:none"> 36</span>
            </div>
            <h4>{{ prosku.unit_name }}</h4>
        </div>
        <div style="background: #eee; height: 10px;"></div>
        <div class="am-tabs detail-list" data-am-tabs>
		  <ul class="am-tabs-nav am-nav am-nav-tabs">
		    <li class="am-active"><a href="#tab1">商品详情</a></li>
		    <li><a href="#tab2">商品评论</a></li>
		  </ul>
		
		  <div class="am-tabs-bd">
		    <div class="am-tab-panel am-fade am-in am-active detail " id="tab1" >
            {{ prosku.sku_introduce|safe }}
		    </div>
		    <div class="am-tab-panel am-fade detail " id="tab2">
		         <ul class="comment-list">
		           <li class="current"><a href="">全部</a></li>
		           <li><a href="">好评（20）</a></li>
		           <li><a href="">中评（5）</a></li>
		           <li><a href="">差评（0）</a></li>
		         </ul>
		         <ul class="comment-pic">
		         	<li>
		         		<div class="tit">
		         			<img src="{% static 'images/tx.png' %}" class="tx" />
		         			<span>songke2014</span>
		         			<i> [2016-01-01]</i>
		         		</div>
		         		<div class="comment-con">
		         			买了些给家人，都说不错！
		         		</div>
		         	</li>
		         </ul>
		    </div>
		  </div>
		</div>
		
		
		<!--底部-->
 <div style=" height: 55px;"></div>
 <ul class="fix-shopping">
 	<li><a href="shopcart.html" class="join">加入购物车</a></li>
 	<li><a href="tureorder.html" class="imm-buy">立即购买</a></li>
 </ul>
{% endblock %}


{% block footer_js %}
<script>
	//购物数量加减
	$(function(){
		$('.increase').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			current_num += 1;
			self.siblings('input').val(current_num);
			update_item(self.siblings('input').data('item-id'));
		})
		$('.decrease').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			if(current_num > 1){
				current_num -= 1;
				self.siblings('input').val(current_num);
				update_item(self.siblings('input').data('item-id'));
			}
		})
	})
</script>
{% endblock %}
 
 
 

market/templates/production/index.html
{% extends 'common/parent.html' %}
{% load static %}

{% block header %}
		<header data-am-widget="header" class="am-header am-header-default sq-head1">
			<div class="am-header-left am-header-nav">
		        <a href="city.html" class="" style="color: #fff;">
			        <img src="{% static 'images/city.png'%}" />
			        <p style="font-size: 12px; margin-top: -35px;">成都</p>
			    </a>
		   </div>
			<h1 class="am-header-title1">
		        <div class="search-box">
		           <a href="{% url 'search:haystack_search'  %}" class="index-search">成都市武侯区∨</a>
		         <!--  <input type="submit" value="" class="search-icon" /> -->
		        </div>
		    </h1>
			<div class="am-header-right am-header-nav">
			    <a href="tidings.html" class="">
		         <div class="messgae"><span>10</span></div>
		        </a>
			</div>
        </header>
<div style="height: 49px;"></div>
{% endblock %}

{% block content %}
<!--图片轮换-->
<div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
  <ul class="am-slides">
        {% for v in banners %}
            <li><img src="{{ MEDIA_URL }}{{ v.banner_url }}"/></li>
        {% endfor %}

  </ul>
</div>
<!--导航-->
 <ul class="sq-nav">
      <li>
        <div class="am-gallery-item">
            <a href="recharge.html" class="">
              <img src="{% static 'images/icon.png'%}" />
              <p>充值</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
              <img src="{% static 'images/icon1.png'%}" />
              <p>签到</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="yhq.html" class="">
              <img src="{% static 'images/icon2.png' %}" />
              <p>红包</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/icon3.png' %}" />
              <p>即将上线</p>
            </a>
        </div>
      </li>
  </ul>
  <ul class="sq-nav1">
  	<li>
        <div class="am-gallery-item">
            <a href="speed.html" class="">
              <img src="{% static 'images/icon4.png' %}" />
              <p>零食飞速</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="category.html" class="">
              <img src="{% static 'images/icon5.png' %}" />
              <p>超市</p>
            </a>
        </div>
      </li>
      
  </ul>
  <div class="h-line"></div>
  <!--不规则展示-->
  <div class="index-product">
  	<div class="index-pro-lf"><a href=""><img src="{% static 'images/s1.png' %}"/></a></div>
  	<div class="index-pro-lr"><a href=""><img src="{% static 'images/s2.png' %}"/></a></div>
  </div>
  <div class="product-bot">
  	<div class="product-bot-lf"><a href=""><img src="{% static 'images/s3.png' %}"/></a></div>
  	<div class="product-bot-lr">
  		<div class="top"><a href=""><img src="{% static 'images/s4.png' %}"/></a></div>
  		<div class="bot">
  			<div class="bot-lf"><a href=""><img src="{% static 'images/s5.png' %}"/></a></div>
  			<div class="bot-lr"><a href=""><img src="{% static 'images/s6.png' %}"/></a></div>
  		</div>
  	</div>
  </div>
  <!--不规则展示-->
  <div class="h-line"></div>
  <!-- 特色专区-->
    {% for zone in act_zones %}
    <div class="sq-title">
 	<img src="{% static 'images/ts.png' %}" width="26"/>
 	{{ zone.region_name }}
  </div>
  <ul data-am-widget="gallery" class="am-gallery pro-list am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default"  >
    #反向查询活动专区商品表
     {% for zgoods in zone.region_sku.all %}
     <li>
        <div class="am-gallery-item">
            <a href="{% url 'production:detail' zgoods.pk  %}" class="">
              <img src="{{ MEDIA_URL }}{{ zgoods.sku_logo }}" />
                <h3 class="am-gallery-title">{{ zgoods.sku_spu_id.spu_name }}&emsp;{{ zgoods.sku_name }}</h3>
                <div class="am-gallery-desc">￥{{ zgoods.sku_price }}</div>
            </a>
        </div>
      </li>
     {% endfor %}


  </ul>
    {% endfor %}

<!--签到-->
<div class="qd-box">
	<div class="popup-title">
			<span>签到成功</span>
			<div class="popup-close"><i class="iconfont">&#xe602</i></div>
	</div>
	<div class="dq-text">
		<img src="{% static 'images/qiandao.png' %}" width="40" />&nbsp; 您已连续签到3天
	</div>
</div>
<!--签到-->
{% block footer %}
 <!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">   
          <li>
            <a href="index.html" class="curr">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="shopcart.html" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="allorder.html" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>
 
          <li>
            <a href="member.html" class="">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>
{% endblock %}
 
 
 
 
 <script type='text/javascript'>
	(function(){
		 new PopUp_api({el:'.index-qd',html:'.qd-box'});
	})()
</script>

{% block footer_js %}
<script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.10&key=7ee8240e4fbe0421f5dfae1b9a239e88&plugin=AMap.CitySearch"></script>
<script type="text/javascript">
    //获取用户所在城市信息
    function showCityInfo() {
        //实例化城市查询类
        var citysearch = new AMap.CitySearch();
        //自动获取用户IP，返回当前城市
        citysearch.getLocalCity(function(status, result) {
            if (status === 'complete' && result.info === 'OK') {
                if (result && result.city && result.bounds) {
                    var cityinfo = result.city;
                    var citybounds = result.bounds;
                    document.getElementById('info').innerHTML = '您当前所在城市：'+cityinfo;
                    //地图显示当前城市
                    map.setBounds(citybounds);
                }
            } else {
                document.getElementById('info').innerHTML = result.info;
            }
        });
    }
    showCityInfo();
</script>

{% endblock %}