market/apps/user/urls.py
from django.conf.urls import url

from user.views import LoginView, RegisterView, SendMsg

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 用户登录
    url(r'^reg/$', RegisterView.as_view(), name="register"),  # 用户注册
    url(r"^send_msg/$",SendMsg.as_view(),name='send_msg'), #发送信息
    #url(r'^member/$', member, name="member"),  # 用户中心
    # url(r'^detail/(?P<id>\d+)/$',detail,name="详情"),
    # url(r'^add/$',add,name="添加"),
    # url(r'^delete/(?P<id>\d+)/$',delete,name="删除"),
    # url(r'^edit/(?P<id>\d+)/$',edit,name="修改"),
    # url(r'^add_form/$',add_form,name="渲染form"),
]

market/market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from production.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 绑定子路由
    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^production/',include('production.urls',namespace='production')),
    url(r'^shoppingcart/', include('shoppingcart.urls', namespace='shoppingcart')),
    url(r'^user/', include('user.urls', namespace='user')),
    #添加富文档子路由
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    #添加搜索子路由
    url(r'^search/', include('haystack.urls', namespace='search')),
]

market/apps/user/models.py
from django.db import models
from django.core.validators import RegexValidator
# Create your models here.
from db.base_model import BaseModel

'''用户模型'''
class User(BaseModel):
    #用户对象属性
    gender_choices=(
        (1,"男"),
        (2,"女"),
        (3,"保密"),
    )
    # user_head = models.ImageField(upload_to='user', verbose_name='头像', default='user/10.jpg', max_length=500)
    user_phone = models.CharField(max_length=11,
                                  verbose_name= "手机号码",
                                  validators=[RegexValidator(r'^1[3-9]\d{9}$',"手机格式错误")])
    user_nickname = models.CharField(max_length=20,
                                     verbose_name='用户名',
                                     null=True,
                                     blank=True) # 用户名
    user_password = models.CharField(max_length=16,
                                     verbose_name='密码')
    user_birth = models.DateField(verbose_name= "生日",
                                  null=True,
                                  blank=True)
    user_gender = models.SmallIntegerField(choices=gender_choices,
                                           default=3,
                                           verbose_name= '性别')
    user_school = models.CharField(max_length=40,
                                   verbose_name="学校",
                                   null=True,
                                   blank=True)
    user_address = models.CharField(max_length=40,
                                    verbose_name="地址",
                                    null=True,
                                    blank=True)
    user_hometown = models.CharField(max_length=43,
                                     verbose_name="籍贯",
                                     null=True,
                                     blank=True)

    def __str__(self):
        return  self.user_nickname

market/apps/user/forms.py
from django import forms
from django_redis import get_redis_connection

from user.helper import set_password
from user.models import User


"""注册表单, 验证"""
class RegisterModelForm(forms.ModelForm):
    # 单独添加字段
    password1 = forms.CharField(max_length=16,
                                min_length=6,
                                error_messages={
                                    'required': '密码必填',
                                    'max_length': '密码长度不能大于32个字符',
                                    'min_length': '密码长度必须大于6个字符',
                                }
                                )
    password2 = forms.CharField(error_messages={'required': "确认密码必填"})

    #验证码
    captcha = forms.CharField(max_length=4,
                              error_messages={
                                  'required':'验证码必须填写'
                              })

    agree = forms.BooleanField(error_messages={'required':'须同意用户协议'})

    class Meta:
        model = User
        # 需要验证的字段
        fields = ['user_phone']

        error_messages = {
            "user_phone": {
                "required": "手机号码必须填写!"
            }
        }

    def clean_user_phone(self):
        # 验证手机号码是否唯一
        user_phone = self.cleaned_data.get('user_phone')
        rs = User.objects.filter(user_phone=user_phone).exists()  # 返回bool
        if rs:
            raise forms.ValidationError("手机号码已经被注册")
        return user_phone


    def clean(self):
        # 验证密码输入
        pwd1 = self.cleaned_data.get("password1")
        pwd2 = self.cleaned_data.get("password2")
        if pwd1 and pwd2 and pwd1 != pwd2:
            raise forms.ValidationError({'pwd2':'两次输入代码不一致'})

        # 验证验证码输入
        try:
            captcha = self.cleaned_data.get('captcha')

            # redis保存
            user_phone = self.cleaned_data.get('user_phone', '')
            # 获取redis中的
            r = get_redis_connection("default")
            random_code = r.get(user_phone)  # 二进制, 转码
            random_code = random_code.decode('utf-8')
            if captcha and captcha != random_code:
                raise  forms.ValidationError({"captcha":"验证码输入错误"})
        except:
            raise forms.ValidationError({"captcha":"验证码输入错误"})
        return  self.cleaned_data




"""登录表单, 验证"""
class LoginModelForm(forms.ModelForm):
    password = forms.CharField(max_length=16,
                               min_length=8,
                               error_messages={
                                   'required': '密码必填',
                                   'max_length': '密码长度不能大于32个字符',
                                   'min_length': '密码长度必须大于6个字符',
                               })

    class Meta:
        model = User
        # 需要验证的字段
        fields = ['user_phone', ]

        error_messages = {
            "user_phone": {
                "required": "手机号码必须填写!"
            }
        }


    def clean(self):
        # 验证用户名
        user_phone = self.cleaned_data.get("user_phone")
        password = self.cleaned_data.get('password')
        # 到数据库去查询
        try:
            user = User.objects.get(user_phone=user_phone)
        except User.DoesNotExist:
            raise forms.ValidationError({"user_phone": "号码错误"})
        # 验证密码
        if user.user_password != set_password(password):
            raise forms.ValidationError({"password": "密码错误!"})
        self.cleaned_data['user'] = user
        return self.cleaned_data

market/apps/user/views.py
import random
import re
import uuid

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views import View

from db.app_common import set_password
from db.base_view import BaseVerifyView
from user.forms import RegisterModelForm, LoginModelForm
from django_redis import get_redis_connection

from user.helper import send_sms
from user.models import User
from django.urls import reverse


# 完成注册功能
class RegisterView(View):
    # get 方法
    def get(self, request):
        # 展示注册的页面
        return render(request, 'user/reg.html')

    # post 方法
    def post(self, request):
        # 接受用户提交的注册信息
        data = request.POST
        form = RegisterModelForm(data)
        if form.is_valid():
            # 数据合法
            cleaned_data = form.cleaned_data
            # 操作数据库, 创建一个用户
            user = User()
            user.user_phone = cleaned_data.get('user_phone')
            # 将密码进行加密
            user.user_password = set_password(cleaned_data.get('password2'))
            # 然后将用户信息保存到数据库
            user.save()
            # 跳转到登录界面
            return redirect(reverse('user:login'))

        else:
            # 不合法
            return render(request, 'user/reg.html', context={"form": form})





#完成登陆功能
class LoginView(View):
    #get 请求获取登录页面
    def get(self,request):
        return  render(request,'user/login.html')
    #post 请求获取用户信息并验证
    def post(self,request):
        #获取数据
        data = request.POST
        #表单验证
        form = LoginModelForm(data)
        if form.is_valid():
            #操作数据库
            #登陆信息保存在session中
            user = form.cleaned_data.get("user")
            request.session['id']=user.pk
            request.session['user_phone']=user.user_phone
            # request.session.set_expiry(0)
            referer = request.session.get('referer')
            #跳转到个人中心
            if referer :
                del request.session['referer']
                return redirect(referer)
            else:
                return redirect(reverse("user:member"))
        else:
            # 数据不合法
            return render(request, 'user/login.html', context={"form": form})




class PersonalCenter(BaseVerifyView):
    def get(self, request):
        tellphone = request.session.get("tellphone")
        context = {
            "tellphone": tellphone
        }
        return render(request, 'user/member.html')

    def post(self, request):

        return render(request, 'user/member.html')


#完成密码忘记功能
class Forget(View):

    def get(self, request):
        return render(request, "user/forgetpassword.html")

    def post(self, request):
        return redirect(reverse("user:login"))

#个人资料
class Info(BaseVerifyView):
    """
    用户个人资料
    """

    def get(self, request):
        tellphone = request.session.get("tellphone")
        user = User.objects.filter(user_telphone=tellphone).first()
        context = {
            "user": user
        }
        return render(request, "user/infor.html", context)

    def post(self, request):
        data = request.POST
        head = request.FILES.get('head')
        tellphone = request.session.get("tellphone")
        user = User.objects.get(user_telphone=tellphone)
        if request.FILES.get("user_head"):
            user.user_head = request.FILES.get("user_head")
            user.user_name = request.POST.get("nickname")
            user.user_gender = request.POST.get("gender")
            user.user_brith = request.POST.get("birth_of_date")
            user.user_school = request.POST.get("school")
            user.user_address = request.POST.get("address")
            user.user_hometown = request.POST.get("hometown")
            user.save()
        return redirect("user:info")

class SendMsg(View):
    """发生短信的视图函数"""
    def post(self,request):
        # 接收到手机号码
        user_phone = request.POST.get("user_phone", "")
        # 后端验证手机号码格式是否正确
        # 创建正则对象
        phone_re = re.compile("^1[3-9]\d{9}$")
        # 匹配传入的手机号码
        rs = re.search(phone_re, user_phone)
        if rs is None:
            # 手机号码格式错误
            return JsonResponse({"error": 1, "errmsg": "手机号码不正确"})
        # 生成随机码 随机数字组成
        random_code = "".join([str(random.randint(0, 9)) for _ in range(4)])

        # 保存随机码到redis中
        # 使用redis, 获取redis连接
        r = get_redis_connection("default")
        # 直接开始操作
        r.set(user_phone, random_code)
        # 设置过期时间
        r.expire(user_phone, 120)
        # 发送短信
        print(random_code)
        key_times ="{}_time".format(user_phone)
        now_times = r.get(key_times)
        if now_times is None or int(now_times) < 50:
            r.incr(key_times)
            #将信息保存1小时，5次请求之后就起到阻隔作用
            r.expire(key_times,3600)
        else:
            return JsonResponse({"error":1,"errmsg":"次数过多"})
        # 使用阿里发生短信

        __business_id = uuid.uuid1()
        params = "{\"code\":\"%s\",\"product\":\"天气不错\"}" % random_code
        print(send_sms(__business_id, user_phone, "注册验证", "SMS_2245271", params))

        return JsonResponse({"error": 0})

market/user/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.
def user(request):
    html = "user "
    return HttpResponse(html)

market/templates/user/forgetpassword.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    超市
{% endblock %}
{% block header %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">忘记密码</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
	    <input type="text" name="user_phone"  placeholder="请输入手机号" class="login-password">
	    <div class="yzm">
	    	<input type="text" class="reg-yzm" placeholder="输入验证码" />
	    	<input type="button" class="yzm-hq" value="获取验证码" />
	    </div>
	    <input type="password" name="password"  placeholder="请输入密码" class="login-password">
	    <input type="password" name="password"  placeholder="确认密码" class="login-name">
	    <input type="submit" class="login-btn" value="立即提交">
{% endblock %}

market/templates/user/infor.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    个人资料
{% endblock %}
{% block head_css %}
    <link href="{% static 'css/check.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">个人资料</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <ul class="safty1">
        <li>
            <i style="margin-top: 25px;">头像</i>
            <div class="infor-pic">
                <img src="{{ MEDIA_URL }}{{ user.head }}"/>
            </div>
        </li>
        <li>
            <input type="file" name="head">
        </li>
        <li>
            <i>昵称</i>
            <input class="infor-tele" name="nickname" value="{{ user.nickname|default:'' }}" placeholder="默认"/>
        </li>
        <li>
            <a href="">
                <i>性别</i>
                <i class="infor-tele">
                    <label class="am-radio-inline">
                        <input type="radio" name="radio10" checked="checked" value="1" data-am-ucheck>男
                    </label>
                    <label class="am-radio-inline">
                        <input type="radio" name="radio10" value="1" data-am-ucheck>女
                    </label>
                </i>
            </a>
        </li>
        <li>
            <a href="">
                <i>生日</i>
                <input class="infor-tele" placeholder="出生日期"/>
            </a>
        </li>

    </ul>

    <div style="height: 10px; background: #efefef;"></div>
    <ul class="safty1">
        <li>
            <i>学校</i>
            <input class="infor-tele" placeholder="就读于哪个学校"/>
        </li>
        <li>
            <i>位置</i>
            <input class="infor-tele" placeholder="详细地址"/>
        </li>
        <li>
            <i>故乡</i>
            <input class="infor-tele" placeholder="来自哪里"/>
        </li>
        <li>
            <i>手机</i>
            <input class="infor-tele" placeholder="13012345678"/>
        </li>
        <li>
            <input type="submit" class="am-btn am-btn-warning" value="保存"/>
        </li>
    </ul>
    </form>
{% endblock %}

market/templates/user/login.html
{% extends  'common/parent.html'%}
{% load static %}

{% block title %}
    登录
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="mobile" id="mobile" placeholder="请输入用户名/手机号" class="login-name">
        <p class="am-text-danger">{{ form.errors.user.phone.0 }}</p>
        <input type="password" name="password" id="password" placeholder="请输入密码" class="login-password">
        <p class="am-text-danger">{{ form.errors.password.0 }}</p>
        <input type="submit" class="login-btn" value="我要登录">
        <div class="agree">
            <a href="{% url 'user:login' %}">免费注册</a>
            <a href="forgetpassword.html" class="forget">忘记密码？</a>
        </div>
        <div class="line"></div>
        <div class="line-text">第三方账号登录</div>
        <ul class="second-login">
            <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
            <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
            <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
        </ul>
    </form>

{% endblock %}

market/templates/user/member.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
   <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>超市</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link href="{% static 'css/amazeui.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'js/popup.mini.js' %}"></script>
	</head>
	<body style="background: #f6f6f6;">
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<h1 class="am-header-title">
  	            <a href="" class="">个人中心</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="member">
	    	<div class="mem-tit">{{ tellphone }}
	    		<a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
	    	</div>
	    	<div class="mem-pic">
		    	<div class="mem-pic-bg" style="background-image: url({% static 'images/memtx.png' %});"></div>
	    	</div>
	    	<ul class="member-menu">
			<li>
				<a href="records.html">
					<p class="yellow">0</p>
					<p class="black">帐户余额 </p>
				</a>
			</li>
            <li>
				<a href="integral.html">
					<p class="yellow">0</p>
					<p class="black">积分 </p>
				</a>
			</li>
			<li>
				<a href="yhq.html">
					<p class="yellow">0</p>
					<p class="black">优惠劵 </p>
				</a>
			</li>
			<li>
				<a href="collect.html">
					<p class="yellow">0</p>
					<p class="black">我的收藏 </p>
				</a>
			</li>
		</ul>
	    </div>
	    <div class="user-list">
		  	<div class="u-list-main">
		  		<img src="{% static 'images/order-pic.png' %}" width="27" />
		  		<span>我的购物订单</span>
		  		<a href="allorder.html">查看全部订单></a>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}">
                    <p>待付款</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}">
                    <p>待收货</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}">
                    <p>待评价</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}">
                    <p>退换货</p></a></li>
		    </ul>
		    <div class="u-list-main">
        <img src="{% static 'images/order-my.png' %}" width="27"/>
        <span>帐户与安全</span>
        </div>
        <ul class="user-nav">
            <li><a href="{% url 'user:info' %}"> <img src="{% static 'images/1-icon4.png' %}">
                <p>个人资料</p></a></li>
            <li><a href="{% url 'user:address' %}"> <img src="{% static 'images/1-icon5.png' %}">
                <p>收货地址</p></a></li>
            <li><a href="saftystep.html"> <img src="{% static 'images/1-icon6.png' %}">
                <p>安全设置</p></a></li>
            <li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}">
                <p>我的钱包</p></a></li>
        </ul>
	    </div>
	    <!--导航-->
<ul class="sq-nav"
    style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
    <li>
        <div class="am-gallery-item">
            <a href="job.html" class="">
                <img src="{% static 'images/m_03.png' %}"/>
                <p>我要兼职</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="recommend.html" class="">
                <img src="{% static 'images/m_04.png' %}"/>
                <p>推荐有奖</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="myrecommend.html" class="">
                <img src="{% static 'images/m_05.png' %}"/>
                <p>我的推荐</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="" class="">
                <img src="{% static 'images/m_06.png' %}"/>
                <p>我的佣金</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="yhq.html" class="">
                <img src="{% static 'images/m_02.png' %}"/>
                <p>我的红包</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="message.html" class="">
                <img src="{% static 'images/m_07.png' %}"/>
                <p>我的动态</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
                <img src="{% static 'images/m_08.png' %}"/>
                <p>客服中心</p>
            </a>
        </div>
    </li>
    <li>
        <div class="am-gallery-item">
            <a href="{% url 'user_info:logout' %}" class="">
                <img src="{% static 'images/m_09.png' %}"/>
                <p>安全退出</p>
            </a>
        </div>
    </li>
</ul>
</div>
    <!--客服中心-->
<div class="qd-box">
    <div class="popup-title">
        <span>客服中心</span>
        <div class="popup-close"><i class="iconfont">&#xe602</i></div>
    </div>
    <div class="dq-text">
        <a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
            <img src="{% static 'images/contactqq.png' %}" width="50"/>
            <p class="contactqq">联系QQ</p>
        </a>
        <a href="tel:0791-12345678">
            <img src="{% static 'images/contacttele.png' %}" width="50"/>
            <p class="contacttele">呼叫电话</p>
        </a>
    </div>
</div>
<!--客服中心-->
      <!--底部-->
<div style="height: 55px;"></div>
<div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
    <ul class="am-navbar-nav am-cf am-avg-sm-5">
        <li>
            <a href="{% url 'product:show' %}" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
        </li>
        <li>
            <a href="{% url 'product:cate' %}" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
        </li>
        <li>
            <a href="{% url 'cart:cart_info' %}" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
        </li>
        <li>
            <a href="allorder.html" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
        </li>

        <li>
            <a href="javascript:;" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
        </li>
    </ul>
</div>


<script type='text/javascript' language="JavaScript">
    (function () {
        new PopUp_api({el: '.index-qd', html: '.qd-box'});
    })()
</script>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/amazeui.min.js' %}"></script>
</body>
</html>

market/templates/user/reg.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    注册
{% endblock %}
{% block header %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">注册</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div style="height: 3rem;"></div>
{% endblock %}

{% block content %}
    <form action="" method="post">
        {%  csrf_token %}
	    <input type="text" name="user_phone" id="user_phone" value="{{ request.POST.user_phone }}" placeholder="请输入手机号" class="login-name">
        <p class="am-text-danger">{{ form.errors.user_phone.0 }}</p>
	    <input type="password" name="password1"  placeholder="请输入密码" class="login-password">
        <p class="am-text-danger">{{ form.errors.password1.0 }}</p>
	    <input type="password" name="password2"  placeholder="确认密码" class="login-name">
        <p class="am-text-danger">{{ form.errors.password2.0 }}</p>
	    <div class="yzm" style="margin-top: 1.5rem;">
	    	<input type="text"  name="captcha" class="reg-yzm" placeholder="输入验证码" />
	    	<input type="button" class="yzm-hq" value="获取验证码" />
	    </div>
        <p class="am-text-danger">{{ form.errors.captcha.0 }}</p>
	     <input type="submit" class="login-btn" value="立即注册">
	    <div class="agree">
	    	<input type="checkbox" name="agree" value="同意" checked="">&nbsp;同意
		    <a href="" class="xy">《用户协议》</a>
            <div class="r-login">已有账号，请<a href="login.html" class="l-login">登录</a></div>
            <p class="am-text-warning">{{ form.errors.agree.0 }}</p>
        </div>

	    </div>
    </form>
{% endblock %}


{% block footer_js %}
    <script type="application/javascript">
    $(function(){
        $(".yzm-hq").on("click", function () {
            //打印
            //验证
            //获取手机号码的文本框的值
            var phone = $('#user_phone').val();
            console.debug(111)
            // 自己判断
            var reg = /^1[3-9]\d{9}$/;
            if (!reg.test(phone)) {
                alert("手机号码不正确");
                return;
            }

            var that = this;
            //发生ajax到后台进行验证
            $.ajax({
                type: "post",
                url: "{% url 'user:send_msg' %}",
                data: {"user_phone": phone, "csrfmiddlewaretoken": "{{ csrf_token }}"},
                dataType: "json",
                success: function (data) {
                    if (data .error == 0) {
                        //发送成功,开始倒计时
                        var count = 60;
                        //颜色变灰
                        $(that).css("background-color", "gray");
                        //不能再点击
                        $(that).prop("disabled", true);
                        var msg = count + "秒后重新发送";
                        var timer = window.setInterval(function () {
                            //周期性执行函数
                            --count;
                            $(that).val(msg);
                            //判断count为0的时候,重新可以点击
                            if (count == 0) {
                                //颜色变灰
                                $(that).css("background-color", "#76bb2a");
                                //不能再点击
                                $(that).prop("disabled",false);
                                //文字显示原来提示
                                $(that).val("获取验证码");
                                //清除定时
                                window.clearInterval(timer);
                                return;
                            }
                            msg = count + "秒后重新发送";
                            $(that).val(msg);

                        }, 1000);//1000是1000ms
                    }else {
                        alert(data.errmsg);
                    }
                }
            })
        });
    })
    </script>
{% endblock %}